FROM quay.io/rhpds/openshift-showroom-terminal-ocp:latest

USER 0

ARG ARGO_CD_CLI_VERSION=v2.14.1
ARG KUSTOMIZE_VERSION=v5.1.0
ARG ROLLOUTS_VERSION=v1.6.4
ARG KUBECTL_NEAT=v2.0.4

# Install various CLI tools required by workshop
RUN curl -sSL https://github.com/argoproj/argo-cd/releases/download/${ARGO_CD_CLI_VERSION}/argocd-linux-amd64 -o /usr/bin/argocd &&\
    chmod +x /usr/bin/argocd &&\
    curl -sSL https://github.com/argoproj/argo-rollouts/releases/download/${ROLLOUTS_VERSION}/kubectl-argo-rollouts-linux-amd64 -o /usr/bin/kubectl-argo-rollouts &&\
    chmod +x /usr/bin/kubectl-argo-rollouts &&\
    mkdir -p /tmp/neat &&\
    curl -sSL https://github.com/itaysk/kubectl-neat/releases/download/${KUBECTL_NEAT}/kubectl-neat_linux_amd64.tar.gz -o /tmp/neat/kubectl-neat.tar.gz &&\
    tar -xvf /tmp/neat/kubectl-neat.tar.gz -C /tmp/neat &&\
    mv /tmp/neat/kubectl-neat /usr/bin/kubectl-neat &&\
    mkdir -p /tmp/kustomize &&\
    curl -sSL https://github.com/kubernetes-sigs/kustomize/releases/download/kustomize%2F${KUSTOMIZE_VERSION}/kustomize_${KUSTOMIZE_VERSION}_linux_amd64.tar.gz -o /tmp/kustomize/kustomize.tar.gz &&\
    tar -xvf /tmp/kustomize/kustomize.tar.gz -C /tmp/kustomize &&\
    mv /tmp/kustomize/kustomize /usr/bin/kustomize &&\
    curl -sSSL https://github.com/mikefarah/yq/releases/download/v4.45.3/yq_linux_amd64 -o /usr/bin/yq &&\
    chmod +x /usr/bin/yq

USER 1001
