ARG TKN_IMAGE_VERSION=v1.11.0

FROM registry.redhat.io/openshift-pipelines/pipelines-cli-tkn-rhel8:${TKN_IMAGE_VERSION}

USER 0

ARG ARGO_CD_CLI_VERSION=v2.7.2
ARG KUSTOMIZE_VERSION=v5.1.0
ARG HELM_VERSION=v3.12.1
ARG POLICYGEN_VERSION=v1.12.2

# Install EPEL
RUN rpm -ivh https://dl.fedoraproject.org/pub/epel/epel-release-latest-8.noarch.rpm &&\
    rpm -ql epel-release

# Install packages
RUN microdnf -y install jq tar gzip siege bc glibc git findutils gettext

# Install oc and argo cd CLI
RUN mkdir -p /tmp/oc &&\
    curl https://mirror.openshift.com/pub/openshift-v4/x86_64/clients/ocp/stable/openshift-client-linux.tar.gz -o /tmp/oc/openshift-client-linux.tar.gz &&\
    tar -xvf /tmp/oc/openshift-client-linux.tar.gz -C /tmp/oc &&\
    mv /tmp/oc/oc /usr/local/bin/oc &&\
    mv /tmp/oc/kubectl /usr/local/bin/kubectl &&\
    curl -sSL https://github.com/argoproj/argo-cd/releases/download/${ARGO_CD_CLI_VERSION}/argocd-linux-amd64 -o /usr/local/bin/argocd &&\
    chmod +x /usr/local/bin/argocd &&\
    curl -sSL https://github.com/argoproj/argo-rollouts/releases/latest/download/kubectl-argo-rollouts-linux-amd64 -o /usr/local/bin/kubectl-argo-rollouts &&\
    chmod +x /usr/local/bin/kubectl-argo-rollouts &&\
    rm -rf /tmp/oc &&\
    mkdir /.siege &&\
    chmod 777 /.siege &&\
    mkdir -p /tmp/kustomize &&\
    curl -sSL https://github.com/kubernetes-sigs/kustomize/releases/download/kustomize%2F${KUSTOMIZE_VERSION}/kustomize_${KUSTOMIZE_VERSION}_linux_amd64.tar.gz -o /tmp/kustomize/kustomize.tar.gz &&\
    tar -xvf /tmp/kustomize/kustomize.tar.gz -C /tmp/kustomize &&\
    mv /tmp/kustomize/kustomize /usr/local/bin/kustomize &&\
    mkdir -p /tmp/helm &&\
    curl -sSL https://get.helm.sh/helm-${HELM_VERSION}-linux-amd64.tar.gz -o /tmp/helm/helm.tar.gz &&\
    tar -xvf /tmp/helm/helm.tar.gz -C /tmp/helm &&\
    mv /tmp/helm/linux-amd64/helm /usr/local/bin/helm &&\
    mkdir -p /etc/kustomize/plugin/policy.open-cluster-management.io/v1 &&\
    curl -sSSL https://github.com/open-cluster-management-io/policy-generator-plugin/releases/download/${POLICYGEN_VERSION}/linux-amd64-PolicyGenerator -o /etc/kustomize/plugin/policy.open-cluster-management.io/v1/policygenerator &&\
    chmod +x /etc/kustomize/plugin/policy.open-cluster-management.io/v1/policygenerator

COPY siege.conf /.siege/siege.conf
COPY ksuid /usr/local/bin/ksuid

USER 1001
